name: Build Android APK from ZIP

on:
  push:
    branches: [ main ] # تم ضبط الفرع الرئيسي بدقة بناءً على تأكيدك

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # هنا يتم فك ضغط ملفك بالاسم الجديد بدقة
    - name: Unzip Project
      run: unzip Work-profile-dpc.zip -d project_folder

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # الانتقال لداخل المجلد وبدء بناء التطبيق
    - name: Build APK
      run: |
        cd project_folder
        chmod +x gradlew
        ./gradlew assembleDebug

    # استخراج ملف الـ APK الجاهز للتحميل بعد انتهاء البناء
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Work-Profile-App
        path: project_folder/app/build/outputs/apk/debug/app-debug.apk

